### ISSUE TITLE
The mapping of concurrencyStamp looks invalid

### ISSUE THREAD

**Issue by Elvin1492** [nhibernate/NHibernate.AspNetCore.Identity#12]
I am getting S**tring or binary data would be truncated.** error during saving the new role to database. ConcurrencyStamp is a guid value, and during the converting to string it gets more length than 32.

![image](https://user-images.githubusercontent.com/4125128/67551572-ef220680-f711-11e9-8bd6-346d74c00087.png)

**Comment by beginor** [comment]
which database are you using, pg, mssql, or mysql ？

**Comment by Elvin1492** [comment]
MsSql. I can add logged query.

**Comment by beginor** [comment]
It will be very nice if you include a logged query!

**Comment by Elvin1492** [comment]
Logged query was added

**Comment by beginor** [comment]
@Elvin1492 Thanks for reporting, I have fix the length mapping of `ConcurrencyStamp`.

Which version of .NET core do you use? The master branch of this project has been update to .NET core 3.0, a new version of this project will be shipped via nuget package.

If you still use 2.2.x , I can make a speciall hotfix release for you.
