### ISSUE TITLE
No persister for: NHibernate.AspNetCore.Identity.IdentityUserRole

### ISSUE THREAD

**Issue by Elvin1492** [nhibernate/NHibernate.AspNetCore.Identity#13]
I am getting this issue when trying to add role to user
I am using fluent mapping as follow, table was successfully created. Also the user and the role is in database already. So they were created successfully.

```
 public class AppUserRoleMap : ClassMapping<AppUserRole>
    {
        public AppUserRoleMap()
        {
            Table("AspNetUserRoles");
            ComposedId(x =>
            {
                Property(y => y.UserId, y =>
                {
                    y.Type(NHibernateUtil.String);
                    y.Length(32);
                    y.Column("UserId");
                });

                Property(y => y.RoleId, y =>
                {
                    y.Type(NHibernateUtil.String);
                    y.Length(32);
                    y.Column("RoleId");
                });
            });
        }
    }
```

**Comment by beginor** [comment]
Because of [the issue](https://github.com/FluentNHibernate/fluent-nhibernate/issues/198) with fluent-nhibernate， it seems `joined-subclass` mapping is not supported by FluentNHibernate now.

  1. Create all mappings for all classes, include `NHibernate.AspNetCore.Identity` 's classes ， please refer to the exists hbm mappings；
  2. Just use `*.hbm.xml` files ， don't use FluentHiberate；
  3. Use [NHibernate.Mapping.Attributes](https://github.com/nhibernate/NHibernate.Mapping.Attributes)， it support `joined-subclass` mapping with the existing hbm xml mapping ， which I have tested with it before。 

> Personaly, I prefer to use xml mapping (*.hbm.xml),  because both `FluentHiberate` and `NHibernate.Mapping.Attributes` will translate it's mapping to xml mapping at runtime. And with the help of NHibernate's xml schema (nhibernate-configuration.xsd and nhibernate-mapping.xsd) file, editing hbm file with intelli popup is easy too.

refer to issue #10 .

**Comment by marcelNgan** [comment]
@beginor have you tried using Nhibernate.Mapping.ByCode? Have the "root entity for AppRole was never registered" MappingException even when using JoinedSubclassMapping<AppRole>. Would love a confirmation or a way around it.

**Comment by Elvin1492** [comment]
@marcelNgan I have already developed fluent-mapping for identity. You can find it in [this ](https://github.com/Elvin1492/NTierAspNetCore)repo.
@beginor , if you want I can create PR for it in here.

**Comment by beginor** [comment]
@Elvin1492 Thanks, but I do not use `fluent-mapping` because of https://github.com/nhibernate/NHibernate.AspNetCore.Identity/issues/13#issuecomment-546645665

**Comment by beginor** [comment]
@marcelNgan I will try using this library with `NHibernate.Mapping.ByCode` , But I think it should be the same as `NHibernate.Mapping.Attributes`, which I had test before.

**Comment by beginor** [comment]
@marcelNgan If you are using with `NHibernate.Mapping.ByCode` , please start with rewriting of `AppRole.hbm.xml` and like this :

```cs
using NHibernate;
using NHibernate.Type;
using NHibernate.Mapping.ByCode.Conformist;
using NHIdentityRole = NHibernate.AspNetCore.Identity.IdentityRole;

namespace WebTest.Entities {

    public class AppRoleMapping : JoinedSubclassMapping<AppRole> {

        public AppRoleMapping() {
            // Add NHIdentityRole as root entity first
            ExplicitDeclarationsHolder.AddAsRootEntity(typeof(NHIdentityRole));
            Extends(typeof(NHIdentityRole));
            Schema("public");
            Table("app_roles");
            Key(k => k.Column("id"));
            Property(
                p => p.Description,
                maping => {
                    maping.Column("description");
                    maping.Type(NHibernateUtil.String);
                    maping.Length(256);
                }
            );
        }

    }

}
```

Then compile the mapping and add them after `AddIdentityMappings` in `Startup.cs`

```cs
var cfg = new Configuration();
var file = Path.Combine(
    AppDomain.CurrentDomain.BaseDirectory,
    "hibernate.config"
);
cfg.Configure(file);
// Add identity mapping based on dialect config (dialet must contains
// PostgreSQL, MySQL or MsSql)
cfg.AddIdentityMappings();
// cfg.AddAssembly(typeof(Startup).Assembly);
var modelMapper = new NHibernate.Mapping.ByCode.ModelMapper();
modelMapper.AddMapping<AppRoleMapping>();
modelMapper.AddMapping<AppUserMapping>();
modelMapper.AddMapping<TodoItemMapping>();
var mappings = modelMapper.CompileMappingForAllExplicitlyAddedEntities();
cfg.AddMapping(mappings);
```

**Comment by beginor** [comment]
@Elvin1492 I think the project of`fluent-mapping` is obsoleted, does not have any update for more then one year. 

if you are interested in using of `NHibernate.Mapping.ByCode`, please keep track of #16 , I will refact to use `NHibernate.Mapping.ByCode`.
