### ISSUE TITLE
SqlException: Incorrect syntax near the keyword 'public'.

### ISSUE THREAD

**Issue by marcelNgan** [nhibernate/NHibernate.AspNetCore.Identity#15]
Hi, trying to modify webtest so it works on MSSQL but somehow im getting the above exception when i'm trying to register a user. 

My hibernate config is this: 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<hibernate-configuration xmlns="urn:nhibernate-configuration-2.2">
  <session-factory>
    <property name="connection.connection_string">Server=.;database=TEST_Data;Trusted_Connection=SSPI; </property>
    <property name="dialect">NHibernate.Dialect.MsSql2008Dialect</property>
    <property name="connection.driver_class">NHibernate.Driver.SqlClientDriver</property>
    <property name="show_sql">true</property>
    <property name="format_sql">true</property>
    <property name="adonet.batch_size">10</property>
    <mapping assembly="WebTest" />
  </session-factory>
</hibernate-configuration>
```

**Comment by beginor** [comment]
As you are using mssql, please change `AddIdentityMappingsForPostgres` to `AddIdentityMappingsForSqlServer` in `Startup.cs`

```diff
  public void ConfigureServices(
      IServiceCollection services
  ) {
  /* ... */
-     cfg.AddIdentityMappingsForPostgres();
+     cfg.AddIdentityMappingsForSqlServer();
```

**Comment by marcelNgan** [comment]
yea done that already... still having this issue...

**Comment by oskarb** [comment]
`public` is a well-known schema name in Postgresql, so it does feel like something, somewhere, is still specifying that. Perhaps log the SQL to find the full SQL statement where this error occurs?

**Comment by beginor** [comment]
Can you create a repo for your work, so I can see what's wrong with your code?

**Comment by marcelNgan** [comment]
Only been doing it by modifying your webtest. I've changed the following:
in hibernate.config
`<property name="connection.connection_string">Server=.;database=TEST_Data;Trusted_Connection=SSPI;</property>
    <property name="dialect">NHibernate.Dialect.MsSql2008Dialect</property>
    <property name="connection.driver_class">NHibernate.Driver.SqlClientDriver</property>` ,
in startup.cs
`cfg.AddIdentityMappingsForSqlServer();`
The issue seems to occur in FindByNameAsync

**Comment by beginor** [comment]
@marcelNgan do you change the mapping files in `test/WebTest/Entities` ? These mapping files are database related, if you use sql server, you should change theme too.

And I have double checked the `sqlserver` brunch, make sure it works with microsoft sql server.

**Comment by marcelNgan** [comment]
@beginor ahh didn't think about that... yup after changing the entities, it does work! Thanks so much!

**Comment by beginor** [comment]
@marcelNgan Anything is welcome!
