### ISSUE TITLE
Refact to use NHibernate.Mapping.ByCode

### ISSUE THREAD

**Issue by beginor** [nhibernate/NHibernate.AspNetCore.Identity#16]
The mapping of `IdentityRole`, `IdentityUser` related entity is xml mapping, The only way to extend these mapping is using subclass mapping like `JoinedSubclassMapping` , but exit mappings of these classes can not be modified.

Refact these mappings to use `NHibernate.Mapping.ByCode` ， allow users to modify these mapping through inheritance。

**Comment by beginor** [comment]
Refact to use NHibernate.Mapping.ByCode from 3.1.3

**Comment by knuxbbs** [comment]
How to override a mapping with `NHibernate.Mapping.ByCode`?
