### ISSUE TITLE
Correct way using of UserManager

### ISSUE THREAD

**Issue by Elvin1492** [nhibernate/NHibernate.AspNetCore.Identity#18]
I am using NHibernate.AspNetCore.Identity and I have two custom columns for user like CityId and CountryId. But while using UserManager the custom Columns are not inserted to the database

Mapping:
```
References(x => x.Country).Column("CountryId");
References(x => x.City).Column("CityId");
```

identity setting
```
services.AddDefaultIdentity<AppUser>(opts =>
                {
                    opts.Password.RequireDigit = false;
                    opts.Password.RequireLowercase = false;
                    opts.Password.RequireUppercase = true;
                    opts.Password.RequireNonAlphanumeric = false;
                    opts.Password.RequiredLength = 7;
                })
                .AddRoles<AppRole>()
                .AddHibernateStores();
```

AppUser class
```
public class AppUser : NHIdentityUser
    {
        public virtual DateTime CreatedDate { get; set; }

        public virtual DateTime LastModifiedDate { get; set; }

        public virtual string DisplayName { get; set; }

        public virtual DateTime? LastLogin { get; set; }

        public virtual int LoginCount { get; set; }

        public virtual int Token { get; set; }

        public virtual int CountryId { get; set; }
        public virtual Country Country { get; set; }

        public virtual int CityId { get; set; }
        public virtual City City { get; set; }
        public virtual string DescriptionAboutAddress { get; set; }

        public virtual IEnumerable<Direction> Directions { get; set; }
    }

```
using UserManager
```
private readonly UserManager<AppUser> _userManager;
//...

 return await _userManager.CreateAsync(user, password);
```

Mappings are correct and I have theses columns in DB.

I just wonder about is there any issue related UserManager?

**Comment by beginor** [comment]
It is a associations (many-to-one and one-to-many) mapping related issue.

you can refer to [SimpleOneToMany](https://github.com/beginor/nhibernate-mapping-samples/tree/master/Samples/Associations%20Mapping/OneToMany/SimpleOneToMany) sample.

or refer to [Association Mappings](https://nhibernate.info/doc/nhibernate-reference/associations.html) of nhibernate's documentation.

**Comment by Elvin1492** [comment]
@beginor it is completely not related with mappings. By meaning mapping everything is correct. It is simple one to many relation, and there is one to many relation in db. So giving CityId value to AppUser, should be enough. But Identity Store does not take additional columns except which we already have,

**Comment by beginor** [comment]
Yes, I it is some thing about mappings. 

Add a many-to-one property to `AppUser` is easy and stright forword:

1. add a virtual `City` property to `AppUser`:

   ```c#
   public class AppUser : NHIdentityUser {
       public virtual DateTime CreateTime { get; set; }
       public virtual DateTime? LastLogin { get; set; }
       public virtual int LoginCount { get; set; }
       // add city property;
       public virtual City City { get; set; }
   }
   ```

2. add a many-to-one property to bindings, if you use xml mappings, it should be:

   ```xml
   <joined-subclass name="AppUser" schema="public"  table="app_users" extends="NHibernate.AspNetCore.Identity.IdentityUser, NHibernate.AspNetCore.Identity, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null">
     <key column="id" />
     <property name="CreateTime" column="create_time" type="datetime" not-null="true" generated="insert" update="false" insert="false" />
     <property name="LastLogin" column="last_login" type="datetime" not-null="false" />
     <property name="LoginCount" column="login_count" type="int" not-null="true" />
     <-- add many to one property -->
     <many-to-one name="City" column="city_id" not-found="ignore" />
   </joined-subclass>
   ```
   and if you use mapping-by-code, it should be:

   ```c#
   ManyToOne(
       e => e.City,
       mapping => {
           mapping.Column("city_id");
           mapping.NotFound(NotFoundMode.Ignore);
       }
   );
   ```

3. create a user with city is some thing like:

   ```c#
   [HttpPost]
   public ActionResult Create() {
       var provider = HttpContext.RequestServices;
       var session = provider.GetService<ISession>();
       var newyork = session.Query<City>()
           .First(c => c.Name == "new york");
       // if your city is not from database, please save it to database first.
       var user = new AppUser() {
           UserName = "newyork_user",
           Email = "newyork_user@newyork.city",
           City = newyork
       };
       var task = userMgr.CreateAsync(user);
       task.Wait();
       var result = task.Result;
       return Ok(user);
   }
   ```

**Comment by beginor** [comment]
@Elvin1492 please check out commit https://github.com/nhibernate/NHibernate.AspNetCore.Identity/commit/c0e812fbeccc38e096e95c9c216292838ce44861

**Comment by Elvin1492** [comment]
As I mentioned before, there is not any problem with mapping. Adding ManyToOne section is not required when you don't need Collections for "One" Side. Adding References is enough for creating ona-to-many relation. But I tried this also, it is not working.(of course will not work, because it is not related with mapping :(  )

**Comment by beginor** [comment]
I am sure the code I checked in works.

**Comment by beginor** [comment]
If you are using fluent-nhibernate mapping, `Reference` is equals to `many-to-one` . 

https://github.com/FluentNHibernate/fluent-nhibernate/wiki/Fluent-mapping#references--many-to-one
