### ISSUE TITLE
Table names in mapping does not match table names in SQL scripts

### ISSUE THREAD

**Issue by XGRATION** [nhibernate/NHibernate.AspNetCore.Identity#22]
The table names in mapping does not match table names in SQL scripts. I would think the underscores (_) should be removed or?

**Comment by XGRATION** [comment]
> 
> 
> The table names in mapping does not match table names in SQL scripts. I would think the underscores (_) should be removed or?

Ahh.. my fault! There are different mapping profiles for MS SQL and Postgre SQL.

**Comment by bruuteuzius** [comment]
Correct :-) postgresql can't have uppercasing

**Comment by XGRATION** [comment]
But I think the table in IdentityUserClaimMappingMsSql should be named AspNetUserClaims to match the table creation scripts and the default naming for "Identity".
