### ISSUE TITLE
Wrong mapping table IdentityUserClaim. True value is AspNetUserClaims

### ISSUE THREAD

**Issue by nguyenvanbien95** [nhibernate/NHibernate.AspNetCore.Identity#24]
https://github.com/nhibernate/NHibernate.AspNetCore.Identity/blob/5376df20fc0c2c1f161bba77e612b4f021e849c9/src/NHibernate.AspNetCore.Identity/Mappings/IdentityUserClaim.cs#L44

**Comment by beginor** [comment]
thanks, I will fix it and make a new release asap.

**Comment by beginor** [comment]
Please update to 3.1.7 。

**Comment by nguyenvanbien95** [comment]
I tried to update to 3.1.7 but this issue have persists.

**Comment by beginor** [comment]
https://github.com/nhibernate/NHibernate.AspNetCore.Identity/blob/3.1.7/src/NHibernate.AspNetCore.Identity/Mappings/IdentityUserClaim.cs#L44

I will try it later.

**Comment by nguyenvanbien95** [comment]
I see. My mistake. Thank you for your fast support.
