### ISSUE TITLE
Oracle Error Identifier is too long

### ISSUE THREAD

**Issue by fairking** [nhibernate/NHibernate.AspNetCore.Identity#26]
Column `lockout_end_unix_time_milliseconds` causes an error on Oracle 11g database.
Error:
```
OracleException (0x80004005): ORA-00972: identifier is too long
```
The column name must be up to 30 characters.

**Comment by beginor** [comment]
sorry， I have not test with oracle before，you can make it the column short for oracle

**Comment by fairking** [comment]
Sure. Just wanna let you know guys.

**Comment by beginor** [comment]
OK，thanks for your report， I will make this field's name shorter in future version

**Comment by fredericDelaporte** [comment]
FYI, NHibernate dialects exposes a `MaxAliasLength` property allowing to know what is the max length a column alias may be, which is usually also the max length for a column name. It can be as low as `18` (`Informix` dialect), and being conservative, that is also its default value if the dialect does not override it.

**Comment by beginor** [comment]
I will change `lockout_end_unix_time_milliseconds` to `lockout_end_unix_time_seconds` next version, which has only 29 characters,  will fix this issue.

existing apps will need a small refact.

**Comment by beginor** [comment]
Version 3.1.8 released， which `change lockout_end_unix_time_milliseconds` to `lockout_end_unix_time_seconds`, need small refact on aspnet_users, please read the release notes.
