### ISSUE TITLE
ConfigurationExtensions.AddIdentityMappings doesn't at the correct mappings for a "property" value of NHibernate.Dialect.MsSql2012Dialect, NHibernate, Version=5.3.0.0, Culture=neutral, PublicKeyToken=aa95f207798dfdb4

### ISSUE THREAD

**Issue by inthegarden** [nhibernate/NHibernate.AspNetCore.Identity#27]
When property variable is "NHibernate.Dialect.MsSql2012Dialect, NHibernate, Version=5.3.0.0, Culture=neutral, PublicKeyToken=aa95f207798dfdb4" the code incorrectly runs cfg.AddIdentityMappingsForPostgres();

Seems as though the condition on the if statement should be > -1 and not >= -1 since -1 means not a match.

**Comment by beginor** [comment]
😅 It's a stupid mistake, I will fix it asap!

**Comment by inthegarden** [comment]
Thank you!

**Comment by beginor** [comment]
I have update a new version, which fixes this issue.

**Comment by inthegarden** [comment]
Excellent, thanks for the quick turn around
