### ISSUE TITLE
NHibernate.ISession still open when using signalr

### ISSUE THREAD

**Issue by MaxenceMouchard** [nhibernate/NHibernate.AspNetCore.Identity#28]
I integrated SignalR into my app some time after using your ISession injection implementation with Identity.

The problem is that signalr is connected with identity and ISession's injected in the identity implementation stay open.

So each Hub from SignalR Keep in Context identity and injected sessions are never kill.

So one session stay open for each Hub.

I was thinking to inject ISessionFactory in identity and open the sessions in the implemented methods for kills Sessions at each end of action but I do not know if this method is suitable, Knowing that the implementation of Users in UserStore is IQueryable so this would not be very safe to do something like:

```
private readonly ISessionFactory _sessionFactory;

public override IQueryable<User> Users
{
    get
    {
        using (ISession session = _sessionFactory.OpenSession())
        {
            return session.Query<User>();
        }
    }
}

public UserStore(ISessionFactory sessionFactory, IdentityErrorDescriber errorDescriber) : base(errorDescriber)
{
    _sessionFactory = sessionFactory;
}
```

what do you think about this case ? 

Thank for your times.

**Comment by gliljas** [comment]
Returning an IQueryable from within a "using session" doesn't work. What is the broader use case?

**Comment by gliljas** [comment]
I don't see how it could work. The session is closed when the IQueryable is returned.

**Comment by MaxenceMouchard** [comment]
Don't get stuck on the Users property, it's not used in my implementation, it's just that Identity requires its implemation. It only works because Users is never called, but my other methods are implemented like this : 

```CSharp
public override async Task < IdentityResult > CreateAsync(User user, CancellationToken cancellationToken = new CancellationToken()) {
    cancellationToken.ThrowIfCancellationRequested();
    ThrowIfDisposed();
    if (user == null) {
        throw new ArgumentNullException(nameof(user));
    }
    using(ISession session = _sessionFactory.OpenSession()) {
        await session.SaveAsync(user, cancellationToken);
        await FlushChangesAsync(session, cancellationToken);
    }
    return IdentityResult.Success;
}

public override async Task < IdentityResult > UpdateAsync(User user, CancellationToken cancellationToken = new CancellationToken()) {
    cancellationToken.ThrowIfCancellationRequested();
    ThrowIfDisposed();
    if (user == null) {
        throw new ArgumentNullException(nameof(user));
    }
    using(ISession session = _sessionFactory.OpenSession()) {
        var exists = await session.Query < User > ().AnyAsync(
            u => u.Id.Equals(user.Id),
            cancellationToken
        );
        if (!exists) {
            return IdentityResult.Failed(
                new IdentityError {
                    Code = "UserNotExist",
                        Description = $ "User with id {user.Id} does not exists!"
                }
            );
        }
        user.ConcurrencyStamp = Guid.NewGuid().ToString("N");


        await session.MergeAsync(user, cancellationToken);
        await FlushChangesAsync(session, cancellationToken);
        return IdentityResult.Success;
    }

}

public override async Task < IdentityResult > DeleteAsync(User user, CancellationToken cancellationToken = new CancellationToken()) {
    cancellationToken.ThrowIfCancellationRequested();
    ThrowIfDisposed();
    if (user == null) {
        throw new ArgumentNullException(nameof(user));
    }
    using(ISession session = _sessionFactory.OpenSession()) {

        await session.DeleteAsync(user, cancellationToken);
        await FlushChangesAsync(session, cancellationToken);
        return IdentityResult.Success;
    }
}

public override async Task < User ? > FindByIdAsync(string userId, CancellationToken cancellationToken = new CancellationToken()) {
    cancellationToken.ThrowIfCancellationRequested();
    ThrowIfDisposed();
    var id = ConvertIdFromString(userId);

    using(ISession session = _sessionFactory.OpenSession()) {
        var user = await session.GetAsync < User > (id, cancellationToken);
        return user;
    }
}
```

**Comment by gliljas** [comment]
That looks like a perfectly viable solution

**Comment by beginor** [comment]
If you are using SignalR Hubs to send message, please follow the rules of hubs <https://learn.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-7.0#create-and-use-hubs>

**Please Note**

Hubs are [transient](https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection#transient):

- Don't store state in a property of the hub class. Each hub method call is executed on a new hub instance.
- Don't instantiate a hub directly via dependency injection. To send messages to a client from elsewhere in your application use an [IHubContext](https://learn.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-7.0).
- Use await when calling asynchronous methods that depend on the hub staying alive. For example, a method such as Clients.All.SendAsync(...) can fail if it's called without await and the hub method completes before SendAsync finishes.

I think the safest useage should be like this:

```c#
public class MessageHub : Hub {

    public async Task SendMessage(string user, string message) {
        var factory = this.Context.GetHttpContext().RequestServices.GetService<ISessionFactory>();
        using var session = factory.OpenSession();
        var users = await session.Query<Users>().ToListAsync();
        await Clients.All.SendAsync("ReceiveMessage", user, users);
    }

}
```

**Comment by MaxenceMouchard** [comment]
Thank you for your advice but i don't use any injection or session inside my hubs. Hubs are clean as you defined the transiant.
My injection comes from UserStore which implements Identity and automatically binds with Signalr Hubs

**Comment by beginor** [comment]
By default `UserStore` and `RoleStore` are registered as `Scoped`, which means they are create per request, this is suitable for web api and mvc. 

If this is not suitable for SignalR, you can register it with another life time. And this is easy, just dont use the default extension method [AddHibernateStores](https://github.com/nhibernate/NHibernate.AspNetCore.Identity/blob/f4611fed90aee6c6a826654bd2137cedee1e669f/src/NHibernate.AspNetCore.Identity/IdentityBuilderExtensions.cs#LL8C3-L8C3) .

PS: Any PR is welcome!
