### ISSUE TITLE
System.Data.SqlClient still required?

### ISSUE THREAD

**Issue by zrhpwr** [nhibernate/NHibernate.AspNetCore.Identity#30]
Hi
In the readme it's stated 
>>Note: When using with SqlServer, you need add System.Data.SqlClient package to your project.

is this still true?
Best regards,
zrhpwr

**Comment by beginor** [comment]
Yes， when you connect to sql server, it's required. but `System.Net.SqlClient` is a .nets tandard 2.0 library now.

**Comment by zrhpwr** [comment]
I'm asking because of this announcement: https://techcommunity.microsoft.com/blog/sqlserver/announcement-system-data-sqlclient-package-is-now-deprecated/4227205
Any plans to switch?

**Comment by beginor** [comment]
`System.Net.SqlClient` is used by [NHibernate.Driver.SqlClientDriver](https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate/Driver/SqlClientDriver.cs). 

If you dont like this driver, you can write your own driver and config hibernate to use it.

And you can also create an issue for [nhibernate-core](https://github.com/nhibernate/nhibernate-core/issues)
