### ISSUE TITLE
MySQL bindings

### ISSUE THREAD

**Issue by devalot76** [nhibernate/NHibernate.AspNetCore.Identity#9]
Hi,
can you give an ETA about adding MySQL bindings, please?
Regards.

**Comment by beginor** [comment]
Want to add MySQL support, please follow these steps:

1. Fork this repo to your account;

2. Create tables required by asp.net core identity with your mysql server, please refer to the `postgresql` and `mssql` directory in the `database` directory, may be you should create `database/mysql` directory for the sql script;

3. Create xml mapping for mysql, and put the xml file to `src/NHibernate.AspNetCore.Identity/Mappings` directory, with name of `AspNetCoreIdentity.mysql.xml`, the path of the file should be:
   ```
   src/NHibernate.AspNetCore.Identity/Mappings/AspNetCoreIdentity.mssql.xml
   ```

4. Add extension methods to file `src/NHibernate.AspNetCore.Identity/ConfigurationExtensions.cs`, you can name it as :
   ```c#
   public static Configuration AddIdentityMappingsForMySql(
       this Configuration cfg
   )
   ```

   Impl it like other two methods.

5. Change nhibernate's config file to use mysql server, and run `UnitTest` and `WebTest` with your mysql server;

6. If you like, please make a pull request to this repo.
